// prints Snail using information about objects generated by the program

class Main : IO {
    main() {
        print_string((new String).get_type().substr(0, 1));
        print_string(self.get_type().substr(3, 1));
        print_string(self.get_type().substr(1, 2));
        print_string((isvoid(self)).get_type().substr(3, 1));
        print_string("\n");
    };
};